/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kian
 */
public class DeuxiemeInterface extends javax.swing.JFrame {

    /**
     * Creates new form DeuxiemeInterface
     */
    public DeuxiemeInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLancer = new javax.swing.JButton();
        jButtonEffacer = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonLancer.setText("Lancer");
        jButtonLancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLancerActionPerformed(evt);
            }
        });

        jButtonEffacer.setText("Effacer");
        jButtonEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEffacerActionPerformed(evt);
            }
        });

        jButtonFermer.setText("Fermer");
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButtonLancer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEffacer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFermer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLancer)
                    .addComponent(jButtonEffacer)
                    .addComponent(jButtonFermer))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEffacerActionPerformed
        // TODO add your handling code here:
        
        jTextArea1.setText(null);
        jLabel1.setText(null);
        nbLancer=1;
    }//GEN-LAST:event_jButtonEffacerActionPerformed

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jButtonFermerActionPerformed

    int nbLancer = 1;
    private void jButtonLancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLancerActionPerformed
        // TODO add your handling code here:
        
        jLabel1.setText("Nombre de Lancers : " + nbLancer);
        nbLancer++;
        
        int r=0;
        String De1,De2,De3,De4,De5,De6,rString="";
        De1 = "  - - -  \n"
            +"|          |\n"
            +"|    0    |\n"   
            +"|          |\n"
            + "  - - -  "    ;
        
        De2 = "  - - -  \n"
            +"|       0 |\n"
            +"|          |\n"   
            +"| 0       |\n"
            + "  - - -  "    ;
        
        
        De3 = "  - - -  \n"
            +"|       0 |\n"
            +"|    0    |\n"   
            +"| 0       |\n"
            + "  - - -  "    ;
        
        De4 = "  - - - - \n"
            +"| 0     0 |\n"
            +"|           |\n"   
            +"| 0     0 |\n"
            + "  - - - - "    ;
        
        De5 = "  - - - - \n"
            +"| 0     0 |\n"
            +"|     0    |\n"   
            +"| 0     0 |\n"
            + "  - - - - "    ;
        
        De6 = "  - - - - \n"
            +"| 0     0 |\n"
            +"| 0     0 |\n"   
            +"| 0     0 |\n"
            + "  - - - - "    ;
                
        r=r+(int)(1+6*Math.random());
        
        if(r==1){rString = De1;}

        if(r==2){rString = De2;}

        if(r==3){rString = De3;}
        
        if(r==4){rString = De4;}
        
        if(r==5){rString = De5;}
       
        if(r==6){rString = De6;}
        
        //rString = String.valueOf(r);
        jTextArea1.setText(rString);
        
    }//GEN-LAST:event_jButtonLancerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeuxiemeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeuxiemeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeuxiemeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeuxiemeInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeuxiemeInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEffacer;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonLancer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
