
import java.awt.Image;
import java.awt.image.RenderedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kian
 */
public class TestComboBox extends javax.swing.JFrame {

    /**
     * Creates new form TestComboBox
     */
    public TestComboBox() {
        initComponents();
    }
    
    private File file;
    private File fImage;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonModifierDef = new javax.swing.JButton();
        jButtonAjouterMot = new javax.swing.JButton();
        jButtonModifierImage = new javax.swing.JButton();
        jButtonSupprMot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir un club :", "Athletico Madrid", "Bayern Munich", "FC Barcelone", "Manchester City", "PSG", "Real Madrid" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonModifierDef.setText("jButton1");
        jButtonModifierDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierDefActionPerformed(evt);
            }
        });

        jButtonAjouterMot.setText("Ajouter Mot");
        jButtonAjouterMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterMotActionPerformed(evt);
            }
        });

        jButtonModifierImage.setText("Modifier Image");
        jButtonModifierImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierImageActionPerformed(evt);
            }
        });

        jButtonSupprMot.setText("Suppr Mot");
        jButtonSupprMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprMotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonModifierImage)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(jButtonModifierDef)))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAjouterMot)
                            .addComponent(jButtonSupprMot))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModifierDef)
                    .addComponent(jButtonAjouterMot))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModifierImage)
                            .addComponent(jButtonSupprMot))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        

        if(jComboBox1.getItemCount()!= 0)
        {
            jTextArea1.setText(null);
            jLabel1.setIcon(null);
            if(jComboBox1.getSelectedItem()=="Choisir un club :") ;
            else
            {
                fImage = new File("Images/"+jComboBox1.getSelectedItem()+".png");                                  
                file = new File("Définition/"+jComboBox1.getSelectedItem()+".txt");
            }
        } 
        
        try
        {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String ligne;
            while (br.ready())
                {
                    ligne = br.readLine();
                    jTextArea1.setText(jTextArea1.getText()+ligne+"\n");                     
                }

               br.close();                  
        }
               
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(ProjetDicoImage.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(ProjetDicoImage.class.getName()).log(Level.SEVERE, null, ex);
        }     
        
        
        try
        {
            Image image = ImageIO.read(fImage);
            jLabel1.setIcon(new javax.swing.ImageIcon(image));
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(TestComboBox.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonModifierDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierDefActionPerformed
        // TODO add your handling code here:
        try
            {
                FileWriter f = new FileWriter(file);
                BufferedWriter out = new BufferedWriter(f);

                out.write(jTextArea1.getText());
                                
                out.flush(); //permet de vider les buffers d'écriture
                out.close();//ferme ce flux
            }
            catch(IOException e)
            {
                
            }   
    }//GEN-LAST:event_jButtonModifierDefActionPerformed

    private void jButtonAjouterMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterMotActionPerformed
        // TODO add your handling code here:
        JOptionPane jop = new JOptionPane();
        String nomclub = jop.showInputDialog(null, "Le nom de votre club :");
        
        String str = evt.getActionCommand();
        jComboBox1.addItem(nomclub);
        
        try 
        {
            FileWriter newDef = new FileWriter("Définition/"+nomclub+".txt");
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(TestComboBox.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAjouterMotActionPerformed

    private void jButtonModifierImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierImageActionPerformed
        // TODO add your handling code here:
        JFileChooser fileImage = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("jpg","png");
        fileImage.setFileFilter(filter);
        int returnValue = fileImage.showOpenDialog(this); // Sélection d'un élement du système de fichier
        if (returnValue == JFileChooser.APPROVE_OPTION)
        {          
            File fic = fileImage.getSelectedFile();                                                                 // la méthode getSelectedFile retourne encapsulée dans un objet File le chemin du fichier sélectionné avec le dialogue ShowOpenDialog
             
            try 
            {
                String tmp= fImage.getName();                                                                       //On crée une variable temporaire qui stock le nom du fichier .png que l'on souhaite modifier
                fImage.delete();                                                                                    //On supprime le fichier .png déjà présent
                Image img = ImageIO.read(fic);
                Image newImg = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(img);
                jLabel1.setIcon(icon);          
                
                File newFileImg = new File("Images/"+fImage.getName());                                             //On crée un nouveau fichier .png qui aura le même nom que celui supprimé précédemment
                ImageIO.write((RenderedImage) img, "png", newFileImg);                                              //Ecrit l'image dans le fichier newFileImg
            } 
            catch (IOException ex) 
            {
                Logger.getLogger(ProjetDicoImage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }       
    }//GEN-LAST:event_jButtonModifierImageActionPerformed

    private void jButtonSupprMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprMotActionPerformed
        // TODO add your handling code here:
        int i=1;
        JOptionPane jop = new JOptionPane();
        String nomclub = jop.showInputDialog(null, "Le nom du club que vous souhaitez enlever :");
        
        //while(i<=jComboBox1.getItemCount())
        //{
            //if(nomclub != jComboBox1.get)                          
                //JOptionPane.showMessageDialog(null, "Le club saisie n'existe pas !");                          
                jComboBox1.removeItem(nomclub);
                JOptionPane.showMessageDialog(null, "Le club a été supprimé !");
                /*else
                JOptionPane.showMessageDialog(null, "Le club saisie n'existe pas !");
                jComboBox1.get*/
        //}       
        
        try 
        {
            FileWriter newDef = new FileWriter("Définition/"+nomclub+".txt");
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(TestComboBox.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSupprMotActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouterMot;
    private javax.swing.JButton jButtonModifierDef;
    private javax.swing.JButton jButtonModifierImage;
    private javax.swing.JButton jButtonSupprMot;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
